apiVersion: skaffold/v4beta1
kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8/*
build:
  local:
    push: false
  artifacts:
    - image: navi23/blackticket-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: .
manifests:
  rawYaml:
    - ./infra/k8s/*
