apiVersion: skaffold/v4beta1
kind: Config
## Old way of doing it.. New way is below with rawYaml:...
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8/*
build:
  local:
    push: false
  artifacts:
    - image: navi23/blackticket-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: .

    - image: rallycoding/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
