apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: blackticket.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000

                  
## Whenever we get a request on our fake website name -> balckticket.dev... with the path of /api/users/:anything... We route it to http://auth-srv:3000 -> http://auth-srv:3000/api/users/:anything
